In [30]:
import random, math
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

def swish(x):
    return x*sigmoid(x)

def relu(x):
    return np.maximum(0,x)

def activation_function(z,act):
    if act=="sigmoid":
        return sigmoid(z)
    elif act == "swish":
        return swish(z)
    elif act == "relu":
        return relu(z)
    elif act=="tanh":
        return np.tanh(z)
    
class Layer():
    def __init__(self,input_size,output_size,act=None):
        self.size = input_size
        self.output_size = output_size
        self.activation = act
        self.weights = np.random.uniform(-1,1,(self.output_size,self.size))    
        self.bias = np.random.uniform(-1,1,(output_size,1))
        self.A = np.random.uniform(-1,1,(output_size,1))
        self.Z = np.random.uniform(-1,1,(output_size,1))
        
    def forward_propagation(self, input_data):
        self.Z = np.dot(self.weights,input_data)+self.bias
        self.A = activation_function(self.Z, self.activation)
        
    def derMSE(self, target):
        return 2*(self.A - target)
    
    def descent(self, input_data, gradient, learningRate):
        
        if(self.activation == "tanh"):
            derZ = 1 - np.power(self.A, 2)
        elif(self.activation == "swish"):
            derZ = swish(self.Z) + sigmoid(self.Z) * (1 - swish(self.Z))
        reps = (self.weights.shape[0], 1)
        derWeights = np.tile(input_data.transpose(), reps)        # Size -> a(L-1)*a(L)
        """derWeights is a matrix with derivatives of Z WRT weights, which is transposed inputs, 
        repeated in rows n-times, where n is number of neurons.
        
    Example:
    
        input_data = [
            [2],
            [1],
            [0]
        ]
        
        derWeights = [
            [2, 1, 0],
            [2, 1, 0],
            [2, 1, 0],
            ... n-rows
        ]
        
        """

        
        """ The below part adds the gradient to the derivative of A WRT input_data and passes this new
        gradient through return, to be used as the gradient for next layer's descent.
            dA/dX is made with 2 steps: adding the backprop gradient to the derivative of A WRT Z and then adding
        the derivative of Z WRT input_data (chain rule).
        
        1.
        Since A is a matrix shaped Nx1, where N is the number of outputs, the receiving gradient from the upper layer
        must be the same shape. Therefore we can multiply the gradient and the derivative together element-wise.
        
    Example:
        
         derZ = [3x1]
         gradient = [3x1]
         firstGrad = [3x1] *(elementwise) [3x1] = [3x1]
        
        """
        firstGrad = np.multiply(gradient, derZ)             # ∂C/∂a(L) * ∂(act)/∂Z    a(L)*1 * a(L)*1 = a(L)*1
        
        """
        2.
        What's left is adding the gradient of Z WRT input_data. 
        
        This turns out to be the weights matrix. Now we have to multiply the firstGrad gradient to these weights 
        element-wise but since the firstGrad is Nx1 shape and the weights are NxM, where M are the features, 
        we need to reshape the gradient matrix to match the weights matrix by cloning gradient's columns:
        """
        secondGrad = np.tile(firstGrad, (1, self.weights.shape[1]))          #Size -> a(L)*1 -> a(L)*a(L-1)
        
        """
        Finally we multiply (E-W) secondGrad to the weights matrix:
        """
        finalGrad = np.multiply(self.weights,secondGrad)         #Size -> a(L)*a(L-1) * a(L)*a(L-1) = a(L)*a(L-1)
        
        """But because same inputs are multiplied with many weights, we can sum those weights together. It turns out
        that we can sum columns to do that"""
        
        finalGrad = np.sum(finalGrad, axis=0, keepdims=True)       #Size -> 1*a(L-1) 
        derBias = 1
        
        weightGrad = np.multiply(derWeights, np.tile(firstGrad, (1, self.weights.shape[1])))
        self.weights = self.weights - learningRate * weightGrad
        self.bias = self.bias - learningRate * firstGrad
        
        """We return transposed matrix, because we desire inputs with a shape of Nx1 and right now finalGrad is 
        transposed"""
        return finalGrad.transpose()     # Size -> a(L-1)*1
    
        
class NeuralNetwork():
    def __init__(self):
        self.layers=[]
        self.epochs=10
        self.learning_rate = 0.008
    
    def add_layer(self,input_size,output_size,activation=None):
        new_layer = Layer(input_size,output_size,activation)
        self.layers.append(new_layer)
        
    def forward_propagation(self,layer_no):
        current_layer = self.layers[layer_no-1]
        prev_layer = self.layers[layer_no-2]
        act = current_layer.activation
        input_data = prev_layer.A
        self.Z = np.dot(weights,input_data)+self.bias
        result = activation_function(self.Z,act)    # array containing neuron values
        current_layer.A = result            #After forward propogation, fills in the neurons in that layer
        return result
    
    def full_forward_propagation(self, input_data):
        #print("layer 0 forward_propagation")
        
        self.layers[0].forward_propagation(input_data)        # From input data to first layer
        for i in range(1, len(self.layers)):
            #print("layer " + str(i) + " forward_propagation")
            
            self.layers[i].forward_propagation(self.layers[i-1].A)      #From layer i-1 to layer i 
        return self.layers[len(self.layers)-1].A
    
    def back_propagation(self, input_data, target):
        gradient = self.layers[len(self.layers)-1].derMSE(target)     # ∂C/∂a(L)   Size -> a(L)*1
        for i in range(0, len(self.layers)-1):
            index = len(self.layers)-1 - i
            #print("Layer " + str(index) + " backpropagation")
            gradient = self.layers[index].descent(self.layers[index-1].A, gradient, self.learning_rate)   #a(L)*1
        self.layers[0].descent(input_data, gradient, self.learning_rate)
            
            
    def predict(self,test_data):
        self.layers[0].forward_propagation(test_data)
        for i in range(1, len(self.layers)):
            self.layers[i].forward_propagation(self.layers[i-1].A)
        return self.layers[len(self.layers)-1].A

train_data = np.array([[[3],[2],[1]],
                      [[5],[1],[1]],
                      [[5],[0],[0]],
                      [[3],[0],[1]],
                      [[4],[-1],[2]],
                      [[3],[-1],[5]],
                      [[3],[-1],[11]],
                      [[3],[1],[3]],
                      [[-1],[1],[1]],
                      [[2],[0],[1]],
                      [[0],[0],[1]],
                      [[3],[0],[5]],
                      [[2],[-1],[6]],
                      [[1],[1],[-4]],
                      [[0],[0],[-1]],
                      [[2],[1],[-4]],
                      [[2],[1],[-1]],
                      [[1],[0],[-1]],
                      [[10],[4],[-2]]])

"""Here we generate target_data set using formula 2*x0 + -4*x1 + -x2"""
target_data = []
for i in range(0, len(train_data)):
    if train_data[i][0]*2 + train_data[i][1]*-4 + train_data[i][2]*1 > 0:
        target_data.append([[1], [0]])
    else:
        target_data.append([[0], [1]])

network = NeuralNetwork()
network.add_layer(3, 1, "tanh")
network.add_layer(1, 2, "tanh")
network.add_layer(2, 2, "swish")

for i in range(0, 800):
    for j in range(0,len(train_data)):
        print("----------------")
        print("Input_data:\n" + str(train_data[j]))
        print("Forward pass:\n" + str(network.full_forward_propagation(train_data[j])))
        print("Target Data:\n" + str(target_data[j]))
        network.back_propagation(train_data[j], target_data[j])
print("Prediction : ", network.predict([0,0,2]))



----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[-0.04473316]
 [ 1.01055241]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[-0.04440637]
 [ 1.01007662]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[-0.03942208]
 [ 0.96891032]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[-0.04726835]
 [ 0.9382152 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[-0.0834258 ]
 [ 0.91806346]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[-0.21960623]
 [ 0.70065022]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[-0.23175695]
 [ 0.62009149]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[-0.05055808]
 [ 0.860129  ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.06572654]
 [

----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[0.6936234 ]
 [0.30230755]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[0.73191954]
 [0.29161813]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.64291299]
 [0.31625158]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[0.70105359]
 [0.31538899]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.68196969]
 [0.32815865]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.64283931]
 [0.34450139]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.67618724]
 [0.3338241 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.68414451]
 [0.32752643]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[0.66666326]
 [0.340195

 [-2]]
Forward pass:
[[0.68191777]
 [0.32620197]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.68989081]
 [0.32006548]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[0.67200235]
 [0.33285721]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[0.68035168]
 [0.32649448]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[0.68660939]
 [0.32069894]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[0.69550825]
 [0.314534  ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[0.70053806]
 [0.30927336]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[0.70995167]
 [0.30328195]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[0.72038575]
 [0.29720376]]
Target Data:
[[1], [0]]
----------------
Inpu

----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[0.72550099]
 [0.28566831]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.60945001]
 [0.32051122]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[0.70784941]
 [0.30658131]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.69141497]
 [0.31895375]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.64287188]
 [0.33901266]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.68630752]
 [0.32453452]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.69431076]
 [0.31832947]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[0.67599071]
 [0.33137261]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[0.68440829]
 [0.3249183 ]

----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[0.74868822]
 [0.28228511]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[0.69794009]
 [0.29279726]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.56747259]
 [0.33604125]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[0.70797546]
 [0.30617451]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.6995609]
 [0.3164686]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.63828308]
 [0.34176415]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.69610713]
 [0.3214483 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.70408627]
 [0.31513437]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[0.68489093]
 [0.32862698

Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[0.62541759]
 [0.3261814 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[0.77272549]
 [0.27975067]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.70144474]
 [0.30243325]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[0.79608496]
 [0.26547383]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[0.80265858]
 [0.26021242]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[0.14333124]
 [0.46603789]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.39664836]
 [0.41175391]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[0.44802676]
 [0.40283852]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0

 [0.21350416]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.75182784]
 [0.2619922 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[0.85867636]
 [0.19889478]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[0.86394298]
 [0.19486348]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.08019389]
 [ 0.74228944]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.25227021]
 [0.61144276]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[0.06414814]
 [0.73076611]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.79866972]
 [0.23997691]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.57218012]
 [0.39170519]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2

----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.7387804 ]
 [0.26018815]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[0.88585533]
 [0.1567972 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[0.89037115]
 [0.15363353]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.094882  ]
 [ 0.94407641]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.1895178 ]
 [0.77160198]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[0.05341308]
 [0.89262104]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.80969089]
 [0.21101883]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.57356154]
 [0.40129202]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.87491238]
 [0.1635

 [1]]
Forward pass:
[[0.72707777]
 [0.25202073]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[0.9076815]
 [0.1192865]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[0.91142627]
 [0.11701726]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.11104606]
 [ 1.04223152]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.15127443]
 [0.85478313]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[0.03185648]
 [0.97558722]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.81213066]
 [0.18705992]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.5795883 ]
 [0.38473627]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.89549322]
 [0.12527603]]
Target Data:
[[1], [0]]
----------

 [1]]
Forward pass:
[[0.8928786 ]
 [0.11556551]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.72562775]
 [0.24206895]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[0.91647921]
 [0.10190924]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[0.91987846]
 [0.10005021]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.12358881]
 [ 1.06960884]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.13760942]
 [0.87868106]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.01257192]
 [ 1.02867192]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.79084279]
 [0.191479  ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.57169604]
 [0.38346181]]
Target Data:
[[1], [0]]
---------

----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[0.89950299]
 [0.10863591]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.73170676]
 [0.23438665]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[0.92510004]
 [0.09395284]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[0.92817242]
 [0.09228478]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.13372297]
 [ 1.06598544]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.13062957]
 [0.88560011]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.06987078]
 [ 1.06067294]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.72325669]
 [0.2437051 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.53410911]
 [0.42151

 [1]]
Forward pass:
[[0.74744061]
 [0.22168359]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[0.94778367]
 [0.07899905]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[0.95002372]
 [0.07765211]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.14105587]
 [ 1.05592453]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.12203524]
 [0.89512417]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.11971918]
 [ 1.06218214]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.48945993]
 [0.47058534]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.44043125]
 [0.52788324]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.94433762]
 [0.08201391]]
Target Data:
[[1], [0]]
------

----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[1.00378661]
 [0.03516535]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[0.98251184]
 [0.04685831]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[0.01037813]
 [1.00803042]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[0.95451601]
 [0.06332307]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.74049261]
 [0.22000958]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[1.01497693]
 [0.02941081]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[1.01509569]
 [0.02867747]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.12847345]
 [ 1.05792703]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.21717514]
 [0.78394937]]

Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[1.03713102]
 [0.00411598]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.056586 ]
 [-0.0070444]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[1.03367361]
 [0.00406503]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.05749043]
 [-0.00931265]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.05528012]
 [-0.00924257]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.05360271]
 [-0.00940353]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[0.96892271]
 [0.0373387 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.10078617]
 [ 1.10106413]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[

 [0.1462361 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.23773374]
 [0.76730881]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.05271683]
 [-0.02469353]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.06666978]
 [-0.03248781]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.048087  ]
 [-0.02419649]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.06474133]
 [-0.03326218]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.0620924 ]
 [-0.03292963]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.05981429]
 [-0.03272833]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[0.98561152]
 [0.00604617]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 

----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.06288481]
 [-0.03995341]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.06030552]
 [-0.03958064]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.05795572]
 [-0.03926919]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 0.99923239]
 [-0.00968307]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.12270866]
 [ 1.10812854]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.01030066]
 [-0.01578252]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.61876269]
 [0.29194112]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.06558171]
 [-0.04234997]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.06432319]
 

----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.12418298]
 [ 1.09967804]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.01639763]
 [-0.02263494]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.64289245]
 [0.26477665]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.0619916 ]
 [-0.04369389]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.06034118]
 [-0.04372786]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.12836422]
 [ 1.09161589]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.22533539]
 [0.78699646]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.08609345]
 [ 1.10213125]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.20359272]
 

----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.12985744]
 [ 1.08184416]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.21426262]
 [0.8100734 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.09351582]
 [ 1.09800714]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.19170833]
 [0.8411832 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.6892703 ]
 [0.21893521]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.83074145]
 [0.09880825]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.18996099]
 [0.84874935]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.05502442]
 [-0.0385603 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.05982745]
 [-0.0

 [1]]
Forward pass:
[[ 1.04937643]
 [-0.03749827]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.05335094]
 [-0.03993106]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.05117243]
 [-0.03959092]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.04909529]
 [-0.03925698]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02006045]
 [-0.02595806]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.12511783]
 [ 1.08108858]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02296127]
 [-0.02760231]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.68828063]
 [0.21836225]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.05499146]
 [-0.04120679]]
Target Data:
[[1], [0]]
---

 [-0.03796404]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.04674921]
 [-0.0376463 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02264957]
 [-0.02696677]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.12535798]
 [ 1.0730096 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02447479]
 [-0.02806661]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.70666233]
 [0.20005154]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.05218019]
 [-0.03932053]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.05031452]
 [-0.03911119]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.13093616]
 [ 1.06343159]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 

----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.10605673]
 [ 1.07895471]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.1647776]
 [0.8974144]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.72903422]
 [0.17923681]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.85931339]
 [0.07457037]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.16534645]
 [0.90029828]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.05044545]
 [-0.03551639]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.05200415]
 [-0.03680089]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.04646346]
 [-0.03500437]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.04836314]
 [-0.0363

 [-0.03502825]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.0450662]
 [-0.0335384]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.04636207]
 [-0.03459347]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.04447136]
 [-0.03430993]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.04266065]
 [-0.03402748]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02538236]
 [-0.02692876]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.12554334]
 [ 1.05835745]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02591055]
 [-0.02739629]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.73870786]
 [0.16829047]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 

Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.1526966 ]
 [0.92457806]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.04746046]
 [-0.03250612]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.04807456]
 [-0.03329333]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.04371912]
 [-0.03204055]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.04456415]
 [-0.03286197]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.04274598]
 [-0.03259469]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.04100425]
 [-0.0323281 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02594219]
 [-0.02637731]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward p

 [3]]
Forward pass:
[[ 1.02620157]
 [-0.02572498]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.12514025]
 [ 1.04731129]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02612047]
 [-0.02591239]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.76219691]
 [0.14512273]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.04375079]
 [-0.0317579 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.04204916]
 [-0.03153592]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.1300207 ]
 [ 1.03770596]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.17117357]
 [0.89954626]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.11112142]
 [ 1.06158141]]
Target Data:
[[0], [1]]
--

 [0]]
Forward pass:
[[ 1.04457817]
 [-0.02980375]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.04102865]
 [-0.02890727]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.04123217]
 [-0.02939483]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.03954717]
 [-0.02915864]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.03793279]
 [-0.02892271]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.0262906 ]
 [-0.02471608]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.124529  ]
 [ 1.04122044]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02596689]
 [-0.02479799]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.77510457]
 [0.13246396]]
Target Data:
[[1], [0]]
---

 [-2]]
Forward pass:
[[0.89091122]
 [0.0489288 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.13686974]
 [0.95208077]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.04332625]
 [-0.02796342]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.04317807]
 [-0.02834285]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.03989969]
 [-0.02756215]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.03990753]
 [-0.0279474 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.03827521]
 [-0.0277238 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.0367113 ]
 [-0.02750035]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02621356]
 [-0.02386618]]
Target Data:
[[1], [0]]
-------

 [0.92476334]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.11225959]
 [ 1.04726471]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.13084054]
 [0.95945246]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.78298427]
 [0.12418757]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.8953722 ]
 [0.04536822]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.13275476]
 [0.95862786]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.04218137]
 [-0.02667594]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.04189178]
 [-0.02697845]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.03884072]
 [-0.02629264]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2

 [-1]]
Forward pass:
[[0.78936437]
 [0.11764252]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.89943881]
 [0.0421421 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.12898803]
 [0.96436569]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.04110892]
 [-0.02546594]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.04070684]
 [-0.02570674]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.03784872]
 [-0.02509958]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.0375804 ]
 [-0.02533977]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.03604053]
 [-0.02513849]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.03456531]
 [-0.02493721]]
Target Data:
[[1], [0]]
------

[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.03691986]
 [-0.02398082]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.03655371]
 [-0.02416933]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.03505469]
 [-0.02397796]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.03361867]
 [-0.02378654]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02556718]
 [-0.02134474]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.12089113]
 [ 1.02649586]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02485661]
 [-0.02127407]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.80717556]
 [0.10146418]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.036

 [ 1.03690512]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.11959292]
 [0.97630969]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.80115991]
 [0.10561065]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.90684062]
 [0.03633602]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.12208681]
 [0.9741575 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.03908817]
 [-0.02318231]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.03851795]
 [-0.02332952]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.03598003]
 [-0.02284826]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.03552915]
 [-0.02299182]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 

----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.03323227]
 [-0.02180842]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.03186896]
 [-0.02163538]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02495963]
 [-0.01972855]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.11822129]
 [ 1.02106253]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02416431]
 [-0.01963044]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.81985019]
 [0.0895188 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.0348171 ]
 [-0.02197617]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.03340944]
 [-0.02181031]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.12158497]
 

 [ 1.01887051]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02383304]
 [-0.01889757]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.8252162 ]
 [0.08454117]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.03396642]
 [-0.02100715]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.03259008]
 [-0.02084832]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.12001326]
 [ 1.01119606]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.1391627 ]
 [0.94974687]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.10890837]
 [ 1.03148294]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.11332792]
 [0.98458779]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0

----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.11061484]
 [0.9878857 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.8156467 ]
 [0.09107318]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.91572294]
 [0.02953818]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.11367968]
 [0.98457449]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.03655191]
 [-0.02031852]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.03583552]
 [-0.02038191]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.03363659]
 [-0.02002594]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.0330264 ]
 [-0.02008415]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.03166869]
 [-0.01

 [1]]
Forward pass:
[[0.11130499]
 [0.98716467]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.0358275]
 [-0.0195024]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.03508024]
 [-0.01954748]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.03296783]
 [-0.01922189]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.0323237 ]
 [-0.01926166]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.0309944 ]
 [-0.01911173]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.02972112]
 [-0.01896154]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02401866]
 [-0.01759636]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.11369273]
 [ 1.01501581]]
Target Data:
[[0], [1]]
-----

Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.02911526]
 [-0.01820259]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02371903]
 [-0.01696969]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.11213378]
 [ 1.01345789]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02285285]
 [-0.01685543]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.83946383]
 [0.07162758]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.03169129]
 [-0.01840431]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.03040092]
 [-0.01826513]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.11489199]
 [ 1.0064991 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forwar

----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.92264126]
 [0.02444253]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.10695154]
 [0.9914633 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.03449938]
 [-0.01801024]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.03370627]
 [-0.01802728]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.03174253]
 [-0.0177521 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.03104749]
 [-0.01776385]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.02977011]
 [-0.01762663]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.02854657]
 [-0.01748908]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02342527]
 [-0.0

----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.12669439]
 [0.96322565]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.10282732]
 [ 1.02217206]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.1012037 ]
 [0.99781453]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.83060743]
 [0.07656092]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.92465944]
 [0.0230007 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.10494232]
 [0.99324207]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.03388893]
 [-0.017327  ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.03307904]
 [-0.01733336]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.03117973]
 [-0.0170

Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.92686309]
 [0.02145391]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.10271745]
 [0.99505653]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.03321665]
 [-0.01657729]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.03239117]
 [-0.01657334]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.03056022]
 [-0.01634105]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.02982845]
 [-0.01633203]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.02860107]
 [-0.01620703]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.02742542]
 [-0.01608163]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pas

 [-0.01592316]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.03179059]
 [-0.01591137]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.03001744]
 [-0.01569705]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.02927251]
 [-0.01568033]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.02806809]
 [-0.01556092]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.02691442]
 [-0.01544107]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02251953]
 [-0.01462075]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.10533265]
 [ 1.00844456]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02164178]
 [-0.01451066]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [

Forward pass:
[[ 1.02874763]
 [-0.01506675]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.02756498]
 [-0.01495261]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.02643216]
 [-0.01483801]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02223519]
 [-0.01409477]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.10359858]
 [ 1.00749444]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.0213595 ]
 [-0.01398705]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.85824493]
 [0.05552913]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02865614]
 [-0.01493832]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.02748506]
 [-0.0148268 ]]
Target Data:
[[1], [0]]
---------

 [1.00459248]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.84368714]
 [0.06453724]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.93228485]
 [0.0177898 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.09707532]
 [0.99892474]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.03153771]
 [-0.01472377]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.03068552]
 [-0.01470016]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.02901449]
 [-0.01451643]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.02825084]
 [-0.01448824]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.02708888]
 [-0.01437908]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [

----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.0278149]
 [-0.013983 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.02667117]
 [-0.0138782 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.02557559]
 [-0.01377289]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02171252]
 [-0.0131555 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.10030655]
 [ 1.00594938]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.0208442]
 [-0.013053 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.86417357]
 [0.05073874]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02768859]
 [-0.0138479 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.0265566 ]
 [-0.

 [-0.01336638]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.02614297]
 [-0.01326785]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.10063926]
 [ 0.99994529]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.11395968]
 [0.97286627]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.09388505]
 [ 1.01501569]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.08920672]
 [1.00678714]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.84895364]
 [0.05993019]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.93530769]
 [0.01584782]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.09380441]
 [1.00069916]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1

 [-1]]
Forward pass:
[[0.11223394]
 [0.97387478]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.09252207]
 [ 1.01423294]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.08761007]
 [1.00767008]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.85131607]
 [0.05791445]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.93665488]
 [0.01500848]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.09231339]
 [1.00140005]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.0301583 ]
 [-0.01323254]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.02929606]
 [-0.01319846]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.02774616]
 [-0.0130489 ]]
Target Data:
[[1], [0]]
----------

----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.02549651]
 [-0.01248646]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.02445032]
 [-0.01239324]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02099315]
 [-0.01192061]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.09559223]
 [ 1.00420688]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02014124]
 [-0.0118265 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.87190258]
 [0.04475392]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02641858]
 [-0.01244015]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.02533865]
 [-0.01234938]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.09731612]
 

 [-4]]
Forward pass:
[[-0.09576567]
 [ 0.99883155]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.10879596]
 [0.97569553]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.08973277]
 [ 1.012798  ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.08444853]
 [1.00921548]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.85593671]
 [0.0540703 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.93927394]
 [0.01342627]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.08935095]
 [1.00260374]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.02931952]
 [-0.01234638]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.02845591]
 [-0.01230808]]
Target Data:
[[1], [0]]
-------

----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.08799179]
 [1.00307642]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.02893961]
 [-0.01195143]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.0280765 ]
 [-0.01191168]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.02662683]
 [-0.01178841]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.0258449 ]
 [-0.01174501]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.02478439]
 [-0.0116596 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.02376839]
 [-0.01157359]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02053993]
 [-0.01117783]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.09254161]
 [ 1

 [0.9771456 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.08713328]
 [ 1.01163208]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.08160133]
 [1.01038699]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.86003476]
 [0.05077678]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.94157889]
 [0.01209113]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.08666999]
 [1.0034909 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.028573  ]
 [-0.01157459]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.027711 ]
 [-0.0115337]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.02629034]
 [-0.01141767]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]

----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.02417732]
 [-0.01096813]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.0231872 ]
 [-0.01088815]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02014377]
 [-0.01055176]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.089842  ]
 [ 1.00264677]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.01931844]
 [-0.01046849]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.88047791]
 [0.0385053 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02499494]
 [-0.01091022]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.02397433]
 [-0.01083237]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.09130015]
 

Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.02559956]
 [-0.01067065]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.02481981]
 [-0.0106249 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.02380316]
 [-0.01054921]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.02282906]
 [-0.01047288]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.01989524]
 [-0.01017036]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.08813867]
 [ 1.00227969]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.01907885]
 [-0.01009032]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.88288576]
 [0.03683185]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02459179]
 [-0.01048915]]
Targe

----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.02253073]
 [-0.0101316 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.01968569]
 [-0.00985574]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.08669949]
 [ 1.0019986 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.0188772 ]
 [-0.00977843]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.88488242]
 [0.0354726 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02425617]
 [-0.01014342]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.0232667 ]
 [-0.01007208]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.08802512]
 [ 0.9977346 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.10082631]
 [

----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.01868077]
 [-0.0094804 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.88680142]
 [0.03419105]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.0239324 ]
 [-0.00981434]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.02295665]
 [-0.00974579]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.0865637 ]
 [ 0.99760069]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.09933527]
 [0.97957309]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.08171257]
 [ 1.00962259]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.0758709 ]
 [1.01216567]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.86811781]
 [0

----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.09799353]
 [0.98000749]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.08055024]
 [ 1.00925362]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.07466779]
 [1.01244894]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.86979018]
 [0.04341215]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.94699453]
 [0.00918165]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.08008097]
 [1.00496293]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.02678289]
 [-0.00980574]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.02593464]
 [-0.0097624 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.02464862]
 [-0.0096

----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.02648319]
 [-0.00952279]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.0256385 ]
 [-0.00947946]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.02437397]
 [-0.00939922]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.02360369]
 [-0.00935311]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.0226395 ]
 [-0.00928843]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.02171552]
 [-0.00922307]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.01910174]
 [-0.00901325]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.08268932]
 [ 1.00134098]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.01831667]
 [

 [1]]
Forward pass:
[[ 1.02619174]
 [-0.00925164]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.02535083]
 [-0.00920843]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.02410691]
 [-0.00913247]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.02333962]
 [-0.00908658]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.02238687]
 [-0.0090242 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.02147382]
 [-0.00896112]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.01892549]
 [-0.00876903]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.08148301]
 [ 1.00117581]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.01814785]
 [-0.00870146]]
Target Data:
[[1], [0]]
-

 [3]]
Forward pass:
[[ 1.01875288]
 [-0.00853441]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.08030491]
 [ 1.00102773]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.01798265]
 [-0.00846899]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.8934201 ]
 [0.02996349]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02280553]
 [-0.00870656]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.02187784]
 [-0.0086474 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.08138431]
 [ 0.99727613]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.09405336]
 [0.98114464]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.07711973]
 [ 1.0082709 ]]
Target Data:
[[0], [1]]
--

Forward pass:
[[0.07007145]
 [1.01327416]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.87611598]
 [0.03901744]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.95044835]
 [0.0075026 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.07566093]
 [1.00548234]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.02560908]
 [-0.00872198]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.02477666]
 [-0.00867926]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.02357318]
 [-0.0086114 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.02281275]
 [-0.00856618]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.02188289]
 [-0.00850827]]
Target Data:
[[1], [0]]
---------------

----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.89635351]
 [0.02818784]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02230042]
 [-0.00823079]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.02139441]
 [-0.00817565]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.07903011]
 [ 0.99719639]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.09164632]
 [0.98174742]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.07501667]
 [ 1.00773856]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.0690176 ]
 [1.01341003]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.87755456]
 [0.03806121]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.95122696]
 [

 [ 0.99717303]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.09057984]
 [0.98199441]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.07408412]
 [ 1.00751782]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.06807467]
 [1.01351594]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.87883876]
 [0.03722124]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.95191977]
 [0.00683041]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.07372709]
 [1.00561308]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.02509989]
 [-0.00827319]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.02427583]
 [-0.00823115]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]

----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.07283177]
 [1.005656  ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.02486474]
 [-0.00807052]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.02404484]
 [-0.00802886]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.02289157]
 [-0.00797046]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.02214157]
 [-0.00792652]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.02124096]
 [-0.00787407]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.0203777 ]
 [-0.00782089]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.01810908]
 [-0.00769933]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.0759529 ]
 [ 1

----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.07187633]
 [ 1.00702972]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.06584967]
 [1.01371005]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.8818598 ]
 [0.03529599]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.95354113]
 [0.00611986]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.07156227]
 [1.00569909]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.02453177]
 [-0.00778861]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.02371804]
 [-0.00774755]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.02258673]
 [-0.00769307]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.02184197]
 [-0.00

Forward pass:
[[0.07078798]
 [1.00571567]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.02432886]
 [-0.00761976]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.02351906]
 [-0.00757911]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.02240099]
 [-0.00752693]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.02165958]
 [-0.00748415]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.02078002]
 [-0.00743544]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.01993685]
 [-0.007386  ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.01777313]
 [-0.00728854]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.07371627]
 [ 1.00041105]]
Target Data:
[[0], [1]]
---------

 [-0.00726079]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.01975714]
 [-0.00721283]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.01763499]
 [-0.00712454]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.0728047 ]
 [ 1.00035054]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.01691537]
 [-0.00707231]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.90295877]
 [0.02441511]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02114824]
 [-0.00719867]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.02029192]
 [-0.00715216]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.07363028]
 [ 0.99714561]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 

----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.02125344]
 [-0.00712284]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.02039163]
 [-0.00707717]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.01956542]
 [-0.00703077]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.01748687]
 [-0.00695186]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.07183298]
 [ 1.00029185]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.0167742 ]
 [-0.00690126]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.90417041]
 [0.02375719]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02093444]
 [-0.00701568]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.02008738]
 

 [ 5]]
Forward pass:
[[ 1.02017955]
 [-0.006886  ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.01936261]
 [-0.0068412 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.01732934]
 [-0.00677178]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.07080637]
 [ 1.00023608]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.01662412]
 [-0.00672288]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.90544621]
 [0.02307586]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02070845]
 [-0.00682524]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.01987117]
 [-0.00678182]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.07157012]
 [ 0.99716789]]
Target Data:
[[0], [1]]
--