![image](dcdw.png)

In [31]:
import random, math
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

def swish(x):
    return x*sigmoid(x)

def relu(x):
    return np.maximum(0,x)

def activation_function(z,act):
    if act=="sigmoid":
        return sigmoid(z)
    elif act == "swish":
        return swish(z)
    elif act == "relu":
        return relu(z)
    elif act=="tanh":
        return np.tanh(z)
    
class Layer():
    def __init__(self,input_size,output_size,act=None):
        self.size = input_size
        self.output_size = output_size
        self.activation = act
        self.weights = np.random.uniform(-1,1,(self.output_size,self.size))    
        self.bias = np.random.uniform(-1,1,(output_size,1))
        self.A = np.random.uniform(-1,1,(output_size,1))
        self.Z = np.random.uniform(-1,1,(output_size,1))
        
    def forward_propagation(self, input_data):
        self.Z = np.dot(self.weights,input_data)+self.bias
        self.A = activation_function(self.Z, self.activation)
        
    def derMSE(self, target):
        return 2*(self.A - target)
    
    def descent(self, input_data, gradient, learningRate):
        
        if(self.activation == "tanh"):
            derZ = 1 - np.power(self.A, 2)
        elif(self.activation == "swish"):
            derZ = swish(self.Z) + sigmoid(self.Z) * (1 - swish(self.Z))
        reps = (self.weights.shape[0], 1)
        derWeights = np.tile(input_data.transpose(), reps)        # Size -> a(L-1)*a(L)
        """derWeights is a matrix with derivatives of Z WRT weights, which is transposed inputs, 
        repeated in rows n-times, where n is number of neurons.
        
    Example:
    
        input_data = [
            [2],
            [1],
            [0]
        ]
        
        derWeights = [
            [2, 1, 0],
            [2, 1, 0],
            [2, 1, 0],
            ... n-rows
        ]
        
        """

        
        """ The below part adds the gradient to the derivative of A WRT input_data and passes this new
        gradient through return, to be used as the gradient for next layer's descent.
            dA/dX is made with 2 steps: adding the backprop gradient to the derivative of A WRT Z and then adding
        the derivative of Z WRT input_data (chain rule).
        
        1.
        Since A is a matrix shaped Nx1, where N is the number of outputs, the receiving gradient from the upper layer
        must be the same shape. Therefore we can multiply the gradient and the derivative together element-wise.
        
    Example:
        
         derZ = [3x1]
         gradient = [3x1]
         firstGrad = [3x1] *(elementwise) [3x1] = [3x1]
        
        """
        firstGrad = np.multiply(gradient, derZ)             # ∂C/∂a(L) * ∂(act)/∂Z    a(L)*1 * a(L)*1 = a(L)*1
        
        """
        2.
        What's left is adding the gradient of Z WRT input_data. 
        
        This turns out to be the weights matrix. Now we have to multiply the firstGrad gradient to these weights 
        element-wise but since the firstGrad is Nx1 shape and the weights are NxM, where M are the features, 
        we need to reshape the gradient matrix to match the weights matrix by cloning gradient's columns:
        """
        secondGrad = np.tile(firstGrad, (1, self.weights.shape[1]))          #Size -> a(L)*1 -> a(L)*a(L-1)
        
        """
        Finally we multiply (E-W) secondGrad to the weights matrix:
        """
        derX = np.multiply(self.weights,secondGrad)         #Size -> a(L)*a(L-1) * a(L)*a(L-1) = a(L)*a(L-1)
        
        """But because same inputs are multiplied with many weights, we can sum those weights together. It turns out
        that we can sum columns to do that"""
        
        derX = np.sum(derX, axis=0, keepdims=True)       #Size -> 1*a(L-1) 
        derBias = 1
        
        weightGrad = np.multiply(derWeights, np.tile(firstGrad, (1, self.weights.shape[1])))
        self.weights = self.weights - learningRate * weightGrad
        self.bias = self.bias - learningRate * firstGrad
        
        """We return transposed matrix, because we desire inputs with a shape of Nx1 and right now finalGrad is 
        transposed"""
        return derX.transpose()     # Size -> a(L-1)*1
    
        
class NeuralNetwork():
    def __init__(self):
        self.layers=[]
        self.epochs=10
        self.learning_rate = 0.008
    
    def add_layer(self,input_size,output_size,activation=None):
        new_layer = Layer(input_size,output_size,activation)
        self.layers.append(new_layer)
        
    def forward_propagation(self,layer_no):
        current_layer = self.layers[layer_no-1]
        prev_layer = self.layers[layer_no-2]
        act = current_layer.activation
        input_data = prev_layer.A
        self.Z = np.dot(weights,input_data)+self.bias
        result = activation_function(self.Z,act)    # array containing neuron values
        current_layer.A = result            #After forward propogation, fills in the neurons in that layer
        return result
    
    def full_forward_propagation(self, input_data):
        #print("layer 0 forward_propagation")
        
        self.layers[0].forward_propagation(input_data)        # From input data to first layer
        for i in range(1, len(self.layers)):
            #print("layer " + str(i) + " forward_propagation")
            
            self.layers[i].forward_propagation(self.layers[i-1].A)      #From layer i-1 to layer i 
        return self.layers[len(self.layers)-1].A
    
    def back_propagation(self, input_data, target):
        gradient = self.layers[len(self.layers)-1].derMSE(target)     # ∂C/∂a(L)   Size -> a(L)*1
        for i in range(0, len(self.layers)-1):
            index = len(self.layers)-1 - i
            #print("Layer " + str(index) + " backpropagation")
            gradient = self.layers[index].descent(self.layers[index-1].A, gradient, self.learning_rate)   #a(L)*1
        self.layers[0].descent(input_data, gradient, self.learning_rate)
            
            
    def predict(self,test_data):
        self.layers[0].forward_propagation(test_data)
        for i in range(1, len(self.layers)):
            self.layers[i].forward_propagation(self.layers[i-1].A)
        return self.layers[len(self.layers)-1].A

train_data = np.array([[[3],[2],[1]],
                      [[5],[1],[1]],
                      [[5],[0],[0]],
                      [[3],[0],[1]],
                      [[4],[-1],[2]],
                      [[3],[-1],[5]],
                      [[3],[-1],[11]],
                      [[3],[1],[3]],
                      [[-1],[1],[1]],
                      [[2],[0],[1]],
                      [[0],[0],[1]],
                      [[3],[0],[5]],
                      [[2],[-1],[6]],
                      [[1],[1],[-4]],
                      [[0],[0],[-1]],
                      [[2],[1],[-4]],
                      [[2],[1],[-1]],
                      [[1],[0],[-1]],
                      [[10],[4],[-2]]])

"""Here we generate target_data set using formula 2*x0 + -4*x1 + -x2"""
target_data = []
for i in range(0, len(train_data)):
    if train_data[i][0]*2 + train_data[i][1]*-4 + train_data[i][2]*1 > 0:
        target_data.append([[1], [0]])
    else:
        target_data.append([[0], [1]])

network = NeuralNetwork()
network.add_layer(3, 1, "tanh")
network.add_layer(1, 2, "tanh")
network.add_layer(2, 2, "swish")

for i in range(0, 800):
    for j in range(0,len(train_data)):
        print("----------------")
        print("Input_data:\n" + str(train_data[j]))
        print("Forward pass:\n" + str(network.full_forward_propagation(train_data[j])))
        print("Target Data:\n" + str(target_data[j]))
        network.back_propagation(train_data[j], target_data[j])
print("Prediction : ", network.predict([0,0,2]))



----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[-0.06408639]
 [ 0.17953778]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[-0.0674114 ]
 [ 0.18657033]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[-0.05836903]
 [ 0.18383458]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[-0.0485818 ]
 [ 0.18159001]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[-0.03907919]
 [ 0.17865714]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[-0.0284927 ]
 [ 0.17661435]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[-0.01413573]
 [ 0.17882522]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[-0.00538986]
 [ 0.17393479]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[0.16736908]
 [0

[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.65582108]
 [0.32088301]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.67167275]
 [0.3113078 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.67631284]
 [0.31053252]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[0.65967874]
 [0.31874639]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[0.67152893]
 [0.31233538]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[0.68242962]
 [0.30659187]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[0.69410029]
 [0.30020911]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[0.70432843]
 [0.29483912]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[0.71010461]
 [0.2

----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[0.66781563]
 [0.31674111]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[0.67942383]
 [0.31033865]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[0.68987372]
 [0.30464381]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[0.70145791]
 [0.29824005]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[0.71144567]
 [0.29279137]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[0.71845386]
 [0.28913403]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[0.72703824]
 [0.2845007 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[0.47661888]
 [0.52152748]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[0.72998272]
 [0.28424739]]
Targ

 [0.29480262]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[0.72170195]
 [0.28666627]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.6911329 ]
 [0.30327347]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.66777917]
 [0.31661551]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.68915832]
 [0.30455016]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.68327056]
 [0.30829761]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[0.67628546]
 [0.31219491]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[0.6877108 ]
 [0.30586866]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[0.69773792]
 [0.30033496]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forwa

 [0.26062234]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[0.78341514]
 [0.25561245]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[0.70757452]
 [0.29876622]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.69467174]
 [0.30497185]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[0.71852025]
 [0.28981227]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.69335408]
 [0.30335556]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.67513873]
 [0.31361318]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.70573242]
 [0.29665804]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.68402306]
 [0.30891316]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]

 [0.3109426 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.65314803]
 [0.33741824]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[0.84698595]
 [0.2252718 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[0.85776316]
 [0.21899072]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[0.85958736]
 [0.21705818]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[0.87067923]
 [0.21062206]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[0.87605088]
 [0.2069216 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[0.88117849]
 [0.20333058]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[0.87486192]
 [0.20527539]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward 

[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[0.96216426]
 [0.12572371]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[0.97114999]
 [0.12036471]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[0.96608202]
 [0.12174288]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[0.97575391]
 [0.11606671]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[0.97700483]
 [0.11436776]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[0.97817846]
 [0.11271149]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[0.95755082]
 [0.1216526 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.0631583 ]
 [ 0.99333581]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[0.95741845]
 [0.12

----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[0.99840053]
 [0.06644401]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.68938527]
 [0.25110355]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[1.04377775]
 [0.04584092]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[1.04290813]
 [0.04489346]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.16009859]
 [ 1.16757039]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.31165473]
 [0.57047155]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.10575753]
 [ 1.0782056 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.26324833]
 [0.6211467 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.69475178]
 [0.24932

----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[1.06005234]
 [0.01331426]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[1.04883546]
 [0.01724404]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[1.05644167]
 [0.0125762 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[1.053978  ]
 [0.01249899]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[1.05167908]
 [0.01239495]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[1.00252547]
 [0.0349646 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.16495131]
 [ 1.19600262]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[1.0146209 ]
 [0.02815099]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.6418512 ]
 [0.26533454]]
Ta

 [0.75569458]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.05696728]
 [-0.00127843]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.06209648]
 [-0.00481273]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.05220683]
 [-0.00132173]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.05794352]
 [-0.0050534 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.05539972]
 [-0.00495254]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.05300016]
 [-0.00486926]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[1.01030882]
 [0.01499555]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.15365905]
 [ 1.18768485]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]


----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.65221639]
 [0.25278573]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.05909116]
 [-0.01665369]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.05695216]
 [-0.01666957]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.1406427 ]
 [ 1.17222299]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.21965117]
 [0.70098267]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.10487526]
 [ 1.1197291 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.19221002]
 [0.73413941]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.69107479]
 [0.22202423]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.81925032]
 [

Forward pass:
[[ 1.02363481]
 [-0.00739783]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.6644764 ]
 [0.24447918]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.0565974 ]
 [-0.02166821]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.05444172]
 [-0.02158797]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.12997731]
 [ 1.16195578]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.2149349 ]
 [0.72303121]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.09879308]
 [ 1.11923571]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.18856863]
 [0.75481573]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.69638627]
 [0.21846387]]
Target Data:
[[1], [0]]
---------

 [ 1.1530492 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02503849]
 [-0.01295556]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.67871435]
 [0.23429403]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.05395825]
 [-0.02533356]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.05181957]
 [-0.02518102]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.12087706]
 [ 1.15146099]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.20981191]
 [0.74436265]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.09404836]
 [ 1.11726937]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.1841151 ]
 [0.77506627]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0

Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.04974797]
 [-0.02565202]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.04757313]
 [-0.02539232]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.04549617]
 [-0.02513674]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.023815  ]
 [-0.01487227]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.11402541]
 [ 1.14390342]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02616023]
 [-0.0166644 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.69214065]
 [0.22399772]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.05174845]
 [-0.02742693]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forwar

 [ 1.13547934]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.19905184]
 [0.77555622]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.09140282]
 [ 1.11200247]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.17368064]
 [0.80517484]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.71862904]
 [0.20240418]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.85147345]
 [0.09646052]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.16211558]
 [0.82333153]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.05172983]
 [-0.02622762]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.05227291]
 [-0.02734898]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]

Forward pass:
[[0.16786014]
 [0.81776665]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.72655241]
 [0.19616425]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.85813189]
 [0.09082746]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.1580063 ]
 [0.83338473]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.05071001]
 [-0.02705049]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.0508225 ]
 [-0.02793001]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.04643975]
 [-0.02659162]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.04674747]
 [-0.02748317]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.04470538]
 [-0.02721549]]
Target Data:
[[1], [0]]
---------------

 [1]]
Forward pass:
[[0.1535314]
 [0.8426268]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.04972828]
 [-0.02733964]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.04950688]
 [-0.02802921]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.04553773]
 [-0.02687318]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.04549105]
 [-0.02756561]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.04350377]
 [-0.02729969]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.04160431]
 [-0.02703661]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02764576]
 [-0.0206927 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.10837757]
 [ 1.12346847]]
Target Data:
[[0], [1]]
-----

 [-0.02683229]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.04441906]
 [-0.02737938]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.04247811]
 [-0.02711674]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.0406229]
 [-0.0268568]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02821539]
 [-0.02131158]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.10823921]
 [ 1.11844141]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02840413]
 [-0.02192877]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.73769194]
 [0.18637021]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.04549523]
 [-0.02845598]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]

 [ 1.11281076]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.17852777]
 [0.8176865 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.09568684]
 [ 1.10027263]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.15223961]
 [0.84680023]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.74815873]
 [0.17863947]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.87413178]
 [0.07798897]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.1452127 ]
 [0.85794291]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.04796644]
 [-0.02707387]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.04731093]
 [-0.02751079]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]

 [0.17326414]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.8785535 ]
 [0.07454898]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.1412421 ]
 [0.86487716]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.04710661]
 [-0.02672753]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.04629811]
 [-0.02707256]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.04312396]
 [-0.02626342]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.04246006]
 [-0.02659952]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.04060283]
 [-0.02634582]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.03882774]
 [-0.02609459]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [

 [0]]
Forward pass:
[[ 1.04533296]
 [-0.02657711]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.04234666]
 [-0.02584767]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.04155571]
 [-0.02610718]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.03973675]
 [-0.02585843]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.03799833]
 [-0.02561206]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02891166]
 [-0.02177185]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.10888347]
 [ 1.10530628]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.028515  ]
 [-0.02205888]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.76361652]
 [0.16435087]]
Target Data:
[[1], [0]]
---

Forward pass:
[[-0.11018755]
 [ 1.09993811]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.16641437]
 [0.84047158]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.09925138]
 [ 1.09159061]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.13919842]
 [0.86937137]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.76726218]
 [0.16272269]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.88679967]
 [0.06818144]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.13359993]
 [0.87800469]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.04537171]
 [-0.0258033 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.04433693]
 [-0.02600665]]
Target Data:
[[1], [0]]
--------------

----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.77830863]
 [0.15178097]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.04030025]
 [-0.02570443]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.03854906]
 [-0.02546789]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.11036581]
 [ 1.0962001 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.16302718]
 [0.84691685]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.10015178]
 [ 1.08883838]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.13553363]
 [0.87570567]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.7728516 ]
 [0.15798861]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.89035205]
 [

----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.04385834]
 [-0.02485699]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.04269159]
 [-0.02497131]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.0401287 ]
 [-0.02441493]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.03909262]
 [-0.02451797]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.03737702]
 [-0.02428411]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.03573764]
 [-0.02405242]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02871941]
 [-0.02126007]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.10957846]
 [ 1.09415134]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02802823]
 [

----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.03943332]
 [-0.02392097]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.03834664]
 [-0.02398877]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.03666216]
 [-0.02375968]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.0350526]
 [-0.0235327]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02854916]
 [-0.02099782]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.10969838]
 [ 1.09076583]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.0277956 ]
 [-0.02107108]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.79119188]
 [0.14068853]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.03860376]
 [-0.0

 [1]]
Forward pass:
[[ 1.03859744]
 [-0.02330937]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.0374622 ]
 [-0.02334126]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.03581453]
 [-0.02311792]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.03424026]
 [-0.02289663]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02829138]
 [-0.02063705]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.1097558 ]
 [ 1.08673767]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02747657]
 [-0.02067075]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.79843255]
 [0.13441768]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.03763256]
 [-0.02381926]]
Target Data:
[[1], [0]]
---

 [ 1.08391845]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02722902]
 [-0.02036713]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.80338557]
 [0.13011007]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.03695999]
 [-0.02331713]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.03534058]
 [-0.02309769]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.11047199]
 [ 1.0823885 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.15120579]
 [0.87006738]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.10251763]
 [ 1.07794039]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.12275568]
 [0.89815491]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0

 [-0.02195973]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02783244]
 [-0.02004291]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.10964781]
 [ 1.08096558]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02695065]
 [-0.02003092]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.80847186]
 [0.12566959]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.03626195]
 [-0.02278647]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.03467059]
 [-0.0225711 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.11033648]
 [ 1.07944102]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.14882322]
 [0.87487841]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]

 [-0.02227385]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.03403425]
 [-0.02206248]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.11014343]
 [ 1.07661958]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.14658425]
 [0.87944368]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.10297376]
 [ 1.07310646]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.11779104]
 [0.9070854 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.80140737]
 [0.13310333]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.90780871]
 [0.05187385]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.11375669]
 [0.91260626]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1

----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.03342941]
 [-0.02157165]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.10989664]
 [ 1.07391784]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.14447557]
 [0.88377975]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.10306789]
 [ 1.07079529]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.11553683]
 [0.91118006]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.80521165]
 [0.12968153]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.91006577]
 [0.05009561]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.11163507]
 [0.91641538]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.03956829]
 [-

Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.10963614]
 [0.92002328]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.03897307]
 [-0.02141432]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.03762233]
 [-0.02136825]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.03562447]
 [-0.02101919]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.03439662]
 [-0.02096528]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.03287626]
 [-0.02076269]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.03142398]
 [-0.02056191]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02701671]
 [-0.01905187]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward p

----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.91437041]
 [0.0466855 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.10759728]
 [0.92371971]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.03835464]
 [-0.02095128]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.03699763]
 [-0.02089383]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.03505467]
 [-0.02056289]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.03381979]
 [-0.02049816]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.03232339]
 [-0.02029961]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.03089406]
 [-0.02010285]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02672295]
 [-0.0

 [0.10659636]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.03320917]
 [-0.0203609 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.03174193]
 [-0.02016492]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.10883973]
 [ 1.06628118]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.13867142]
 [0.89585833]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.10289528]
 [ 1.06411971]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.10938228]
 [0.92246245]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.81577837]
 [0.12001851]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.91626521]
 [0.04517662]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [

 [ 1.06543061]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02523336]
 [-0.01801367]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.83360852]
 [0.10341901]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.03269214]
 [-0.01993353]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.03124611]
 [-0.01974107]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.10841423]
 [ 1.06401192]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.13698129]
 [0.89939984]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.1027125 ]
 [ 1.06209931]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.1076074 ]
 [0.92573482]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0

 [-0.01779176]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.10756191]
 [ 1.06323008]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02496266]
 [-0.01769857]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.83697005]
 [0.10039942]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.03219854]
 [-0.01952095]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.03077282]
 [-0.01933192]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.10795425]
 [ 1.06183646]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.13537118]
 [0.90277563]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.10247757]
 [ 1.06014808]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [

----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.82439179]
 [0.11195516]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.92124702]
 [0.04118766]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.10115285]
 [0.93546351]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.03632978]
 [-0.01939668]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.0349697 ]
 [-0.01931116]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.03318991]
 [-0.01903157]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.03194938]
 [-0.0189406 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.03053079]
 [-0.01875558]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.029176  ]
 [-0.

 [1]]
Forward pass:
[[0.09946829]
 [0.93853096]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.0357847 ]
 [-0.01896778]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.03442771]
 [-0.0188768 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.03268818]
 [-0.01860928]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.03145   ]
 [-0.01851331]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.03005223]
 [-0.01833202]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.02871739]
 [-0.01815235]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02537862]
 [-0.01714067]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.10653422]
 [ 1.05876036]]
Target Data:
[[0], [1]]
---

Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02416414]
 [-0.01676669]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.84628908]
 [0.09197008]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.03080887]
 [-0.01833469]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.02944061]
 [-0.01815566]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.1063523 ]
 [ 1.05567522]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.13083852]
 [0.91223941]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.10147646]
 [ 1.05455168]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.10124345]
 [0.93745721]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward

 [-0.01794616]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.02901328]
 [-0.01777045]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.10573442]
 [ 1.05369153]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.1293785 ]
 [0.91525765]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.10104176]
 [ 1.05272938]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.09975448]
 [0.94017975]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.83270703]
 [0.10400262]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.92599809]
 [0.03735839]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.09667862]
 [0.94358491]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1

Forward pass:
[[0.12797742]
 [0.91813134]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.10057132]
 [ 1.05097825]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.0983354 ]
 [0.94275989]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.83522418]
 [0.10156255]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.92742523]
 [0.03620476]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.0953262 ]
 [0.94601619]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.03442198]
 [-0.01787538]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.03307881]
 [-0.01777397]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.03143437]
 [-0.01753407]]
Target Data:
[[1], [0]]
----------------


 [-1]]
Forward pass:
[[0.83762869]
 [0.09921784]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.92878375]
 [0.03510577]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.09403361]
 [0.94832369]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.03399135]
 [-0.01752408]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.03265418]
 [-0.01742026]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.03103833]
 [-0.0171884 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.02981726]
 [-0.01708101]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.02848779]
 [-0.01691231]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.02721834]
 [-0.01674513]]
Target Data:
[[1], [0]]
------

 [-0.01685855]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.02783972]
 [-0.01669225]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.10375024]
 [ 1.04824556]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.12533168]
 [0.92347775]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.09953855]
 [ 1.04767993]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.09568386]
 [0.94752839]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.83992833]
 [0.09696311]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.93007868]
 [0.03405788]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.0927959 ]
 [0.95051497]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1

----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.02750786]
 [-0.0163819 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.10310785]
 [ 1.0467106 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.12417306]
 [0.92577818]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.09902656]
 [ 1.04624512]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.09453504]
 [0.9495672 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.84196422]
 [0.09495738]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.93122156]
 [0.03313311]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.09169826]
 [0.95244058]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.03320857]
 [-

----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.10245352]
 [ 1.04523684]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.12304967]
 [0.92798051]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.09849553]
 [ 1.04486296]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.0934287 ]
 [0.95151165]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.84392211]
 [0.09302041]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.93231752]
 [0.0322467 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.0906404 ]
 [0.95427822]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.03285246]
 [-0.01658084]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.03153452]
 [-0.0

 [1]]
Forward pass:
[[0.86362148]
 [0.0760899 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.028137  ]
 [-0.01594683]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.02688031]
 [-0.01578855]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.10178878]
 [ 1.04382163]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.12195882]
 [0.93008969]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.09794757]
 [ 1.04353163]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.09236174]
 [0.95336694]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.84580684]
 [0.09114879]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.93336965]
 [0.03139645]]
Target Data:
[[1], [0]]
--

----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02229428]
 [-0.01455024]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.86558457]
 [0.07428001]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02782683]
 [-0.01566045]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.0265832 ]
 [-0.01550471]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.10111504]
 [ 1.04246244]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.12089808]
 [0.93211036]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.09738459]
 [ 1.04224931]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.09133133]
 [0.95513795]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.84762292]
 [0

 [-0.01520851]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.02549116]
 [-0.01505656]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02306973]
 [-0.01444776]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.10042385]
 [ 1.0423091 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02211255]
 [-0.01433162]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.86731622]
 [0.07268284]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02755188]
 [-0.01540506]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.02631984]
 [-0.0152516 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.10049065]
 [ 1.04126367]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 

Forward pass:
[[ 1.02883245]
 [-0.0152107 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.02765269]
 [-0.01509804]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.02641443]
 [-0.0149471 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.02523228]
 [-0.01479753]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02287153]
 [-0.01421413]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.09975533]
 [ 1.04102336]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02191913]
 [-0.01409836]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.86913586]
 [0.07100431]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02726159]
 [-0.0151339 ]]
Target Data:
[[1], [0]]
---------

----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.11787546]
 [0.93768364]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.09562237]
 [ 1.03867909]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.08843481]
 [0.95998928]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.8526996 ]
 [0.08425471]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.93719328]
 [0.02831813]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.08585517]
 [0.9623035 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.03123636]
 [-0.01520885]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.02995312]
 [-0.015098  ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.02850673]
 [-0.0149

 [0.02756371]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.08491198]
 [0.96381729]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.03091787]
 [-0.01493432]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.02964238]
 [-0.01482347]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.02821432]
 [-0.01464181]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.02704924]
 [-0.01452935]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.02583658]
 [-0.0143836 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.02467893]
 [-0.01423916]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02244237]
 [-0.01370708]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 

 [ 1.03727055]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02133772]
 [-0.01339399]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.8744688 ]
 [0.06608936]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02640237]
 [-0.01432287]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.02521899]
 [-0.01417917]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.09759469]
 [ 1.03633548]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.11589821]
 [0.94116348]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.09434939]
 [ 1.03642618]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.08657265]
 [0.96299278]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0

----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.85741381]
 [0.0795098 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.93978651]
 [0.02624894]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.08324341]
 [0.96642948]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.03035533]
 [-0.01444665]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.02909422]
 [-0.01433618]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.02769799]
 [-0.01416258]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.0265461 ]
 [-0.01405079]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.02535485]
 [-0.01390943]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.02421769]
 [-0.

 [-0.01308625]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.09622169]
 [ 1.03512931]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.02099283]
 [-0.01297444]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.8775412 ]
 [0.06326593]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02590143]
 [-0.01384485]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.02473937]
 [-0.01370552]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.0961848 ]
 [ 1.03424385]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.1140798 ]
 [0.94423556]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.093101  ]
 [ 1.03442297]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [

Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.1131968 ]
 [0.94568056]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.09246971]
 [ 1.03347628]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.08407081]
 [0.96686091]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.86023939]
 [0.07666236]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.94133223]
 [0.02502678]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.08165949]
 [0.9688244 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.0298229 ]
 [-0.01398233]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.02857616]
 [-0.01387261]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:


----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.09471162]
 [ 1.03223285]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.11225833]
 [0.94718171]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.09178181]
 [ 1.03248991]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.08321309]
 [0.96813848]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.86170221]
 [0.07518908]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.9421299 ]
 [0.02440023]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.08083335]
 [0.97003834]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.02954595]
 [-0.01373999]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.02830697]
 [-0.0

 [1]]
Forward pass:
[[0.88189794]
 [0.0592824 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02518317]
 [-0.01315433]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.02405181]
 [-0.01302138]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.09400452]
 [ 1.03132415]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.11140776]
 [0.94851081]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.09114398]
 [ 1.0316142 ]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.08244075]
 [0.96926621]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.86301341]
 [0.07386976]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.94284342]
 [0.02384251]]
Target Data:
[[1], [0]]
--

 [0.94978807]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.09050417]
 [ 1.03077057]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.08168594]
 [0.97034689]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.86428917]
 [0.07258781]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.94353628]
 [0.02330364]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.07936126]
 [0.97213793]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.029054  ]
 [-0.01330855]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.02782925]
 [-0.01320055]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.0265043 ]
 [-0.01304456]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2

 [-0.01198802]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.88450909]
 [0.05691155]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02474801]
 [-0.01273394]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.02363531]
 [-0.0126049 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.09259312]
 [ 1.02960927]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.10974842]
 [0.95101579]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.08986303]
 [ 1.02995782]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.08094768]
 [0.97138276]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.86553136]
 [0.07134173]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 

 [ 1.02923892]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.08028472]
 [0.97229475]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.86664205]
 [0.07022976]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.94481057]
 [0.02232029]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [2]
 [1]]
Forward pass:
[[0.07800934]
 [0.97399104]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.02860411]
 [-0.01291344]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.02739287]
 [-0.01280675]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.02609187]
 [-0.01265654]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.02498577]
 [-0.01254928]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 

 [0.97482637]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[5]
 [1]
 [1]]
Forward pass:
[[ 1.02839581]
 [-0.01273049]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[5]
 [0]
 [0]]
Forward pass:
[[ 1.02719097]
 [-0.01262449]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [1]]
Forward pass:
[[ 1.02590096]
 [-0.01247689]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.02480074]
 [-0.01237039]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.02368432]
 [-0.0122447 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.02261872]
 [-0.01212014]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02078463]
 [-0.011747  ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.09136991]
 [ 1.02881628]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0

[[1], [0]]
----------------
Input_data:
[[ 4]
 [-1]
 [ 2]]
Forward pass:
[[ 1.02457074]
 [-0.01214807]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [ 5]]
Forward pass:
[[ 1.02346425]
 [-0.01202448]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 3]
 [-1]
 [11]]
Forward pass:
[[ 1.02240814]
 [-0.011902  ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02061036]
 [-0.01154251]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.0905665 ]
 [ 1.02791944]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.01973221]
 [-0.01144044]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.88825011]
 [0.05354511]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02411804]
 [-0.01212422]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.

Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.0204518 ]
 [-0.01135703]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.0898234 ]
 [ 1.02712161]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.01958003]
 [-0.01125638]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.88949118]
 [0.05243795]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02390727]
 [-0.01192028]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.02283081]
 [-0.01179891]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.0896784 ]
 [ 1.02643455]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.10644896]
 [0.95564411]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward 

Input_data:
[[3]
 [1]
 [3]]
Forward pass:
[[ 1.02029624]
 [-0.01117567]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[-1]
 [ 1]
 [ 1]]
Forward pass:
[[-0.08908354]
 [ 1.02635598]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[2]
 [0]
 [1]]
Forward pass:
[[ 1.01943085]
 [-0.01107645]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.89069746]
 [0.05136715]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02370152]
 [-0.01172139]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.02263397]
 [-0.0116019 ]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.08892879]
 [ 1.02568883]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.1056219 ]
 [0.95672999]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.08649716]
 [ 1.02615285]]
Targ

----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.89178169]
 [0.05040957]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02351584]
 [-0.01154211]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.02245633]
 [-0.01142433]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.0882405 ]
 [ 1.02502726]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.10486868]
 [0.95769304]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.08585954]
 [ 1.02550827]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.07665749]
 [0.97696427]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.87263514]
 [0.06428327]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.94803506]
 [

----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.89283923]
 [0.04948032]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02333402]
 [-0.01136685]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.0222824 ]
 [-0.01125074]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.08755599]
 [ 1.02439037]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.10412481]
 [0.95861999]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.08522396]
 [ 1.02488703]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.07601603]
 [0.97773169]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.87367995]
 [0.06325895]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.94859398]
 [

----------------
Input_data:
[[0]
 [0]
 [1]]
Forward pass:
[[0.89387136]
 [0.04857824]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[3]
 [0]
 [5]]
Forward pass:
[[ 1.02315588]
 [-0.01119548]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 2]
 [-1]
 [ 6]]
Forward pass:
[[ 1.02211201]
 [-0.01108101]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[ 1]
 [ 1]
 [-4]]
Forward pass:
[[-0.08687549]
 [ 1.02377717]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 0]
 [ 0]
 [-1]]
Forward pass:
[[0.10338993]
 [0.95951233]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-4]]
Forward pass:
[[-0.08459073]
 [ 1.02428828]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 2]
 [ 1]
 [-1]]
Forward pass:
[[0.07538539]
 [0.97846863]]
Target Data:
[[0], [1]]
----------------
Input_data:
[[ 1]
 [ 0]
 [-1]]
Forward pass:
[[0.87470269]
 [0.06226075]]
Target Data:
[[1], [0]]
----------------
Input_data:
[[10]
 [ 4]
 [-2]]
Forward pass:
[[0.94914015]
 [