![image](dcdw.png)

In [1]:
from matplotlib import pyplot as plt
import random, math
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

def swish(x):
    return x*sigmoid(x)

def relu(x):
    return np.maximum(0,x)

def softmax(x):
    p = np.exp(x - np.max(x))
    return p/np.sum(p)

def activation_function(z,act):
    if act=="sigmoid":
        return sigmoid(z)
    elif act == "swish":
        return swish(z)
    elif act == "relu":
        return relu(z)
    elif act=="tanh":
        return np.tanh(z)
    elif act=="softmax":
        return softmax(z)
    
class Layer():
    def __init__(self,input_size,output_size,act=None):
        self.size = input_size
        self.output_size = output_size
        self.activation = act
        self.wx = np.random.uniform(-1,1,(self.output_size,self.size))
        self.wh = np.random.uniform(-1,1,(self.size,self.size))
        self.wy = np.random.uniform(-1,1,(self.size,self.size))
        self.bias = np.random.uniform(-1,1,(output_size,1))
        # Changes required to the below two definitions
        self.A = np.random.uniform(-1,1,(output_size,1,))
        self.Z = np.random.uniform(-1,1,(output_size,1))
        
    def forward_propagation(self, input_data):
        self.Z = np.dot(self.weights,input_data)+self.bias
        self.A = activation_function(self.Z, self.activation)
        
    def derMSE(self, target):
        return 2*(self.A - target)
    
    '''def descent(self, input_data, gradient, learningRate):
        
        if(self.activation == "tanh"):
            derZ = 1 - np.power(self.A, 2)
        elif(self.activation == "swish"):
            derZ = swish(self.Z) + sigmoid(self.Z) * (1 - swish(self.Z))
        reps = (self.weights.shape[0], 1)
        derWeights = np.tile(input_data.transpose(), reps)        # Size -> a(L-1)*a(L)
        """derWeights is a matrix with derivatives of Z WRT weights, which is transposed inputs, 
        repeated in rows n-times, where n is number of neurons.
        
    Example:
    
        input_data = [
            [2],
            [1],
            [0]
        ]
        
        derWeights = [
            [2, 1, 0],
            [2, 1, 0],
            [2, 1, 0],
            ... n-rows
        ]
        
        """

        
        """ The below part adds the gradient to the derivative of A WRT input_data and passes this new
        gradient through return, to be used as the gradient for next layer's descent.
            dA/dX is made with 2 steps: adding the backprop gradient to the derivative of A WRT Z and then adding
        the derivative of Z WRT input_data (chain rule).
        
        1.
        Since A is a matrix shaped Nx1, where N is the number of outputs, the receiving gradient from the upper layer
        must be the same shape. Therefore we can multiply the gradient and the derivative together element-wise.
        
    Example:
        
         derZ = [3x1]
         gradient = [3x1]
         firstGrad = [3x1] *(elementwise) [3x1] = [3x1]
        
        """
        firstGrad = np.multiply(gradient, derZ)             # ∂C/∂a(L) * ∂(act)/∂Z    a(L)*1 * a(L)*1 = a(L)*1
        
        """
        2.
        What's left is adding the gradient of Z WRT input_data. 
        
        This turns out to be the weights matrix. Now we have to multiply the firstGrad gradient to these weights 
        element-wise but since the firstGrad is Nx1 shape and the weights are NxM, where M are the features, 
        we need to reshape the gradient matrix to match the weights matrix by cloning gradient's columns:
        """
        secondGrad = np.tile(firstGrad, (1, self.weights.shape[1]))          #Size -> a(L)*1 -> a(L)*a(L-1)
        
        """
        Finally we multiply (E-W) secondGrad to the weights matrix:
        """
        derX = np.multiply(self.weights,secondGrad)         #Size -> a(L)*a(L-1) * a(L)*a(L-1) = a(L)*a(L-1)
        
        """But because same inputs are multiplied with many weights, we can sum those weights together. It turns out
        that we can sum columns to do that"""
        
        derX = np.sum(derX, axis=0, keepdims=True)       #Size -> 1*a(L-1) 
        derBias = 1
        
        weightGrad = np.multiply(derWeights, np.tile(firstGrad, (1, self.weights.shape[1])))
        self.weights = self.weights - learningRate * weightGrad
        self.bias = self.bias - learningRate * firstGrad
        
        """We return transposed matrix, because we desire inputs with a shape of Nx1 and right now finalGrad is 
        transposed"""
        return derX.transpose()     # Size -> a(L-1)*1
    
        
"""class NeuralNetwork():
    def __init__(self):
        self.layers=[]
        self.epochs=10
        self.learning_rate = 0.008
    
    def add_layer(self,input_size,output_size,activation=None):
        new_layer = Layer(input_size,output_size,activation)
        self.layers.append(new_layer)
        
    def forward_propagation(self,layer_no):
        current_layer = self.layers[layer_no-1]
        prev_layer = self.layers[layer_no-2]
        act = current_layer.activation
        input_data = prev_layer.A
        self.Z = np.dot(weights,input_data)+self.bias
        result = activation_function(self.Z,act)    # array containing neuron values
        current_layer.A = result            #After forward propogation, fills in the neurons in that layer
        return result
    
    def full_forward_propagation(self, input_data):
        #print("layer 0 forward_propagation")
        
        self.layers[0].forward_propagation(input_data)        # From input data to first layer
        for i in range(1, len(self.layers)):
            #print("layer " + str(i) + " forward_propagation")
            
            self.layers[i].forward_propagation(self.layers[i-1].A)      #From layer i-1 to layer i 
        return self.layers[len(self.layers)-1].A
    
    def back_propagation(self, input_data, target):
        gradient = self.layers[len(self.layers)-1].derMSE(target)     # ∂C/∂a(L)   Size -> a(L)*1
        for i in range(0, len(self.layers)-1):
            index = len(self.layers)-1 - i
            #print("Layer " + str(index) + " backpropagation")
            gradient = self.layers[index].descent(self.layers[index-1].A, gradient, self.learning_rate)   #a(L)*1
        self.layers[0].descent(input_data, gradient, self.learning_rate)
            
            
    def predict(self,test_data):
        self.layers[0].forward_propagation(test_data)
        for i in range(1, len(self.layers)):
            self.layers[i].forward_propagation(self.layers[i-1].A)
        return self.layers[len(self.layers)-1].A"""
        '''


class RNN():
    def __init__(self):
        self.layers = []
        self.learning_rate = 0.008
    
    def add_layer(self,input_size,output_size,activation=None):
        new_layer = Layer(input_size,output_size,activation)
        self.layers.append(new_layer)
        
    def forward_propagation(self,layer_no):
        current_layer = self.layers[layer_no-1]
        prev_layer = self.layers[layer_no-2]
        act = current_layer.activation
        input_data = prev_layer.A
        self.Z = np.dot(weights,input_data)+self.bias
        result = activation_function(self.Z,act)    # array containing neuron values
        current_layer.A = result            #After forward propogation, fills in the neurons in that layer
        return result
    
    def full_forward_propagation(self, input_data):
        #print("layer 0 forward_propagation")
        
        self.layers[0].forward_propagation(input_data)        # From input data to first layer
        for i in range(1, len(self.layers)):
            #print("layer " + str(i) + " forward_propagation")
            
            self.layers[i].forward_propagation(self.layers[i-1].A)      #From layer i-1 to layer i 
        return self.layers[len(self.layers)-1].A
    
    def back_propogation_through_time(self,output_data,target):
        
        
network = NeuralNetwork()
network.add_layer(3, 3, "tanh")
network.add_layer(3, 2, "tanh")
network.add_layer(2, 2, "swish")

for i in range(0, 800):
    for j in range(0,len(train_data)):
        if i%95==0 and j%19 == 0:
            print(i,j)
            print("----------------")
            print("Input_data:\n" + str(train_data[j]))
            print("Forward pass:\n" + str(network.full_forward_propagation(train_data[j])))
            print("Target Data:\n" + str(target_data[j]))
            network.back_propagation(train_data[j], target_data[j])
        else:
            network.full_forward_propagation(train_data[j])
            network.back_propagation(train_data[j], target_data[j])
print("------------------------------------------------")
print("Model Training Completed Successfully !!")


IndentationError: expected an indented block (<ipython-input-1-949fda6a32f9>, line 173)

In [3]:
test_data = np.empty((0, 3, 1))
while len(test_data) < 20:
    X_loc = random.random()*2-1
    Y_loc = random.random()*2-1
    radius = random.random()
    test_data = np.append(test_data, [[[X_loc], [Y_loc], [radius]]], axis=0)
for x in test_data:
    print("Prediction :\n {} \n ----------------\n".format(x), network.predict(x),"\n--------------------------------")

Prediction :
 [[-0.00619986]
 [-0.37720284]
 [ 0.6463399 ]] 
 ----------------
 [[0.86187742]
 [0.10832696]] 
--------------------------------
Prediction :
 [[-0.78086656]
 [-0.32564749]
 [ 0.66764041]] 
 ----------------
 [[0.05019719]
 [0.99568981]] 
--------------------------------
Prediction :
 [[0.41540763]
 [0.65871535]
 [0.78331597]] 
 ----------------
 [[0.00845399]
 [1.03813781]] 
--------------------------------
Prediction :
 [[ 0.24722475]
 [-0.24805785]
 [ 0.53004415]] 
 ----------------
 [[0.91786636]
 [0.07840574]] 
--------------------------------
Prediction :
 [[-0.70279271]
 [ 0.46321518]
 [ 0.61447053]] 
 ----------------
 [[0.02247825]
 [1.0280764 ]] 
--------------------------------
Prediction :
 [[-0.17676664]
 [ 0.2792578 ]
 [ 0.2540299 ]] 
 ----------------
 [[0.92570571]
 [0.07711444]] 
--------------------------------
Prediction :
 [[-0.07945405]
 [ 0.11611852]
 [ 0.58647246]] 
 ----------------
 [[0.92530286]
 [0.07696259]] 
--------------------------------
Pr